name: esm-exp
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.2.1
  - torchvision=0.17.1
  - pytorch-cuda=12.2
  - cudatoolkit=12.2
  - numpy=1.24.3
  - scipy=1.13.0
  - pandas=2.2.0
  - matplotlib=3.8.2
  - seaborn=0.13.1
  - pip
  - pip:
    - timm==0.9.12
    - hydra-core==1.3.2
    - omegaconf==2.3.0
    - scikit-learn==1.5.0
    - wandb==0.17.0