# ViT-Small/16 on CIFAR-10 with clean labels
model:
  name: vit_small_patch16_224
  num_classes: 10
  img_size: 32
  
dataset:
  name: cifar10
  root: ./data
  download: true
  label_corruption: false
  corruption_seed: null
  
training:
  batch_size: 512
  epochs: 25
  optimizer:
    type: adamw
    lr: 5e-4
    betas: [0.9, 0.95]
    weight_decay: 1e-2
  scheduler:
    type: cosine
    warmup_steps: 100
  
curvature:
  checkpoints: [100, 500, 2000]
  top_k: 30
  lanczos_max_iter: 80
  batch_size: 512
  
distributed:
  devices: 2
  backend: nccl
  
experiment:
  seeds: [1337, 2024, 9001]
  name: vit_cifar10_clean
  save_dir: ./results
  log_wandb: false
  
compute:
  precision: float32
  compile_model: true